version: "3.8"

services:
  db:
    image: postgres:16
    container_name: users-postgres
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: users
      POSTGRES_PASSWORD: userspass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users -d usersdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: skytv-service-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB_URL: jdbc:postgresql://db:5432/usersdb
      POSTGRES_DB_USERNAME: users
      POSTGRES_DB_PASSWORD: userspass
